#! /bin/bash

if [[ $1 == "test" ]]
then
  PSQL="psql --username=postgres --dbname=worldcuptest -t --no-align -c"
else
  PSQL="psql --username=freecodecamp --dbname=worldcup -t --no-align -c"
fi

# Do not change code above this line. Use the PSQL variable above to query your database.

#EMPTY THE ROWS IN THE TABLES OF THE DATABASE TO RERUN THE FILE
echo $($PSQL "TRUNCATE TABLE games, teams")

#READ games.csv FILE USING CAT AND APPLY A WHILE LOOP TO READ ROW BY ROW
cat games.csv | while IFS="," read YEAR ROUND WINNER OPPONENT WINNER_GOALS OPPONENT_GOALS
do

#INSERT TEAMS TABLE

  #GET WINNER TEAM NAME

  if [[ $YEAR != "year" ]]
  then
#INSERT WINNER
  #GET TEAM_ID
  WINNER_ID=$($PSQL "SELECT team_id FROM teams WHERE name='$WINNER'");


  #IF NOT FOUND
    if [[ -z $WINNER_ID ]]
    then

  #INSERT TEAM
    INSERT_WINNER=$($PSQL "INSERT INTO teams(name) VALUES ('$WINNER')")

  #IF INSERTED SUCCESS
      if [[ $INSERT_WINNER == "INSERT 0 1" ]]
       then
       echo $INSERT_WINNER

  #GET NEW TEAM_ID
      WINNER_ID=$($PSQL "SELECT team_id FROM teams WHERE name='$WINNER'")
      WINNER_NAME=$($PSQL "SELECT name FROM teams WHERE team_id='$WINNER_ID'")
      echo "Insert success : ${WINNER_NAME}"
      fi
    fi
#INSERT OPPONENT

# get winner team_id
    OPPONENT_ID=$($PSQL "SELECT team_id FROM teams WHERE name='$OPPONENT'")
    # if not found
    if [[ -z $OPPONENT_ID ]]
    then
      # insert team
      INSERT_OPPONENT=$($PSQL "INSERT INTO teams(name) VALUES('$OPPONENT')")
      # if inserted success
      if [[ $INSERT_OPPONENT == "INSERT 0 1" ]]
      then 
        echo $INSERT_OPPONENT
        # get new team_id
        OPPONENT_ID=$($PSQL "SELECT team_id FROM teams WHERE name='$OPPONENT'")
        OPPONENT_NAME=$($PSQL "SELECT name FROM teams WHERE team_id='$OPPONENT_ID'")
        echo "Insert success : ${OPPONENT_NAME}"
      fi
    fi
    
    # ---------------------------------------------------------------------------------------
    # insert games
    # ---------------------------------------------------------------------------------------
    INSERT_GAMES=$($PSQL "INSERT INTO games(year,round,winner_id,opponent_id,winner_goals,opponent_goals) VALUES($YEAR,'$ROUND',$WINNER_ID,$OPPONENT_ID,$WINNER_GOALS, $OPPONENT_GOALS)")
    if [[ $INSERT_GAMES == "INSERT 0 1" ]]
    then
      echo $INSERT_GAMES
      echo "Insert success : $YEAR, $ROUND, $WINNER_ID, $OPPONENT_ID, $WINNER_GOALS, $OPPONENT_GOALS"
    fi

  fi 
  
done





